### ISSUE TITLE
Antora configuration missing, needed for publication

### ISSUE THREAD

**Issue by gmarpons** [decidim/docs-social-contract#3]
See https://docs.decidim.org/docs-authoring/en/administration#document-config-file.

Needed in all languages.

**Comment by carolromero** [comment]
Hi @gmarpons, Antora config file updated in all languages

**Comment by gmarpons** [comment]
Thanks @carolromero !

Relevant commits:

* 6fbb6432f53fbaf696fb9080c8f1031a8805938b
* e35abc4a77e3895a45eeb7088ba45e6180870e96
* 3264de3c18eec353f3458ab468aa64d91e137f4b
* 37aab58dbfd87c70bcaf2f2a6904af5053d0522b
